# 多层感知器

In [1]:
from IPython.display import HTML

HTML('<iframe src="https://www.youtube.com/embed/Rs9petvTBLk" width="800" height="450" frameborder="0" allowfullscreen></iframe>')


# 1.实现隐藏层

先修要求
接下来我们会讲神经网络在多层感知器里面的数学部分。讲多层感知器我们会用到向量和矩阵。你可以通过下列讲解对此做个回顾

- 1.可汗学院的 [向量入门](https://www.khanacademy.org/math/linear-algebra/vectors-and-spaces/vectors/v/vector-introduction-linear-algebra).
- 2.可汗学院的 [矩阵入门](https://www.khanacademy.org/math/precalculus/precalc-matrices).


<img src="../../sources/img/NeuralNetworkIntro/gradient-descent-multilayer-perceptron-1.png" alt="" width="1200" height="300" />
<img src="../../sources/img/NeuralNetworkIntro/gradient-descent-multilayer-perceptron-2.png" alt="" width="1200" height="300" />
<img src="../../sources/img/NeuralNetworkIntro/gradient-descent-multilayer-perceptron-3.png" alt="" width="1200" height="300" />
<img src="../../sources/img/NeuralNetworkIntro/gradient-descent-multilayer-perceptron-4.png" alt="" width="1200" height="300" />
<img src="../../sources/img/NeuralNetworkIntro/gradient-descent-multilayer-perceptron-5.png" alt="" width="1200" height="300" />
<img src="../../sources/img/NeuralNetworkIntro/gradient-descent-multilayer-perceptron-6.png" alt="" width="1200" height="300" />
<img src="../../sources/img/NeuralNetworkIntro/gradient-descent-multilayer-perceptron-7.png" alt="" width="1200" height="300" />
<img src="../../sources/img/NeuralNetworkIntro/gradient-descent-multilayer-perceptron-8.png" alt="" width="1200" height="300" />
<img src="../../sources/img/NeuralNetworkIntro/gradient-descent-multilayer-perceptron-9.png" alt="" width="1200" height="300" />
<img src="../../sources/img/NeuralNetworkIntro/gradient-descent-multilayer-perceptron-10.png" alt="" width="1200" height="300" />
<img src="../../sources/img/NeuralNetworkIntro/gradient-descent-multilayer-perceptron-11.png" alt="" width="1200" height="300" />
<img src="../../sources/img/NeuralNetworkIntro/gradient-descent-multilayer-perceptron-12.png" alt="" width="1200" height="300" />

这里的规则是，如果是数组在左边，数组的元素个数必须与右边矩阵的行数一样。如果矩阵在左边，那么矩阵的列数，需要与右边向量的行数匹配。

### 构建一个列向量

看上面的介绍，你有时会需要一个列向量，尽管 NumPy 默认是行向量。你可以用 `arr.T` 来对数组进行转置，但对一维数组来说，转置还是行向量。所以你可以用 `arr[:,None]` 来创建一个列向量：

```
print(features)
> array([ 0.49671415, -0.1382643 ,  0.64768854])

print(features.T)
> array([ 0.49671415, -0.1382643 ,  0.64768854])

print(features[:, None])
> array([[ 0.49671415],
       [-0.1382643 ],
       [ 0.64768854]])
```

当然，你可以创建一个二维数组，然后用 `arr.T` 得到列向量。

```

np.array(features, ndmin=2)
> array([[ 0.49671415, -0.1382643 ,  0.64768854]])

np.array(features, ndmin=2).T
> array([[ 0.49671415],
       [-0.1382643 ],
       [ 0.64768854]])
```

我个人更倾向于保持所有向量为一维数组，这样可以更好认知。

## 编程练习

下面你要实现一个 4x3x2 网络的正向传播，用 sigmoid 作为两层的激活函数。

要做的事情：

- 计算隐藏层的输入
- 计算隐藏层输出
- 计算输出层的输入
- 计算神经网络的输出


## 练习题

In [ ]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)

weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))


# TODO: Make a forward pass through the network

hidden_layer_in = None
hidden_layer_out = None

print('Hidden-layer Output:')
print(hidden_layer_out)

output_layer_in = None
output_layer_out = None

print('Output-layer Output:')
print(output_layer_out)

### 解决方案

In [ ]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)

weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))


# TODO: Make a forward pass through the network

hidden_layer_in = np.dot(X, weights_input_to_hidden)
hidden_layer_out = sigmoid(hidden_layer_in)

print('Hidden-layer Output:')
print(hidden_layer_out)

output_layer_in = np.dot(hidden_layer_out, weights_hidden_to_output)
output_layer_out = sigmoid(output_layer_in)

print('Output-layer Output:')
print(output_layer_out)